# Generated by Django 4.2.4 on 2023-12-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_codes', models.TextField()),
                ('heading', models.CharField(max_length=200)),
                ('home_background', models.ImageField(upload_to='home_background/')),
            ],
        ),
    ]
