# Generated by Django 4.2.4 on 2023-12-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeContent',
        ),
    ]
