# Generated by Django 4.2.4 on 2023-12-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecontent',
            name='home_background',
        ),
        migrations.AddField(
            model_name='homecontent',
            name='brand',
            field=models.CharField(default='InvestiWise', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homecontent',
            name='introduce',
            field=models.CharField(default='InvestiWise', max_length=100),
            preserve_default=False,
        ),
    ]
