# Generated by Django 4.2.4 on 2023-12-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_homecontent_home_background_homecontent_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecontent',
            name='brand',
        ),
        migrations.AddField(
            model_name='homecontent',
            name='brand_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
